name: Python Application CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8 (syntax errors only)
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        # Only check actual project files, not virtual environments
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv,env,.venv,ENV,env.bak,venv.bak,.eggs,*.egg,build,dist,.pytest_cache,htmlcov,.tox,cursor-day01,node_modules
    
    - name: Lint with flake8 (code quality)
      run: |
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=venv,env,.venv,ENV,env.bak,venv.bak,.eggs,*.egg,build,dist,.pytest_cache,htmlcov,.tox,cursor-day01,node_modules
    
    - name: Test with pytest
      run: |
        pytest -v --cov=. --cov-report=term-missing --cov-report=xml
      continue-on-error: false
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: always()
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
